### PR TITLE
Request for Song of Horro Complete Edition

### PR DESCRIPTION
**Pull request by CrovLune**
Game Request
------------

Game requested:
- Song of Horro Complete Edition

# Prerequisites

- I confirm that this game:
  - [ x] is for personal use and will not be sold on.
  - [ x] will not be horded and never used.
- [x ] Email address: macryten@gmail.com

# Checklist

- [x ] Only one game requested.
- [ x] PR title is name of game.
- [x ] Moved game from `AVAILABLE.md` to `CLAIMED.md`.
- [ x] Changed status icon to ❌.

### CODE REVIEW

**Comment by kwilliams1987** [comment]
As mentioned in the checklist, you should make a single pull request per game.

Please make a PR per game, and specify which of the games you prefer. Due to high demand I am currently only giving max 2 games per person.

**Comment by CrovLune** [comment]
> As mentioned in the checklist, you should make a single pull request per game.
> 
> Please make a PR per game, and specify which of the games you prefer. Due to high demand I am currently only giving max 2 games per person.

Requested 1 game

**Comment by kwilliams1987** [comment]
Err your Markdown formatter has completely reformatted the files :|

**Comment by kwilliams1987** [comment]
I have merged this request into my other branch, the link is in your email.

**Comment by CrovLune** [comment]
sorry man :S didn't notice it screwing it up.

**Pull request closed without merging**
