### PR TITLE
CLAIMED.MD

### PR DESCRIPTION
**Pull request by whitetiger21**
Claim for iamai

### CODE REVIEW

**Comment by whitetiger21** [comment]
Thank you! I actually had to study Github because I don't use it and don't know how it works :)

**Comment by kwilliams1987** [comment]
Something has gone wrong here, your merge is conflicting with an update I just created.

Please can you update your fork and recreate your PR with the game you wish to claim.

**Comment by whitetiger21** [comment]
my bad. i wasn't really sure what I was doing. games are
Bear With Me
Crazy Machines 3

**Comment by whitetiger21** [comment]
closing the pull request

**Pull request closed without merging**
