### PR TITLE
Yakuza 0

### PR DESCRIPTION
**Pull request by kwilliams1987**
Game Request
------------

Game requested:

# Prerequisites

- I confirm that this game:
  - [X] is for personal use and will not be sold on.
  - [X] will not be horded and never used.
- [ ] Email address: 

# Checklist

- [X] Only one game requested.
- [X] PR title is name of game.
- [X] Moved game from `AVAILABLE.md` to `CLAIMED.md`.
- [X] Changed status icon to ❌.

### CODE REVIEW

**Comment by ScottSummers616** [comment]
hi, i wanted to do this but i never used this site before, how do i make a pull request? my head hurts trying to understand just by looking at it and i dont wanna mess anything up

**Comment by kwilliams1987** [comment]
I will make a PR for you but might take a few days as I am mostly offline
for the holidays.

**Comment by ScottSummers616** [comment]
it is ok, i dont mind waiting, i am pretty clueless on how stuff works here, i am still learning.
  may i ask, i can choose one game only i image right? if so, that would be Yakuza Kiwami 2 or Catherine Classic, which one is the not claimed

**Comment by kwilliams1987** [comment]
If you are going to play the games, or give them to people who will, you're
free to request as many games as you want.

Requesting games to horde or sell for profit is not allowed.

I reserve the right to reject requests if I don't think they are made in
good faith.

**Pull request merged**
