### PR TITLE
Claim Slay the Spire

### PR DESCRIPTION
**Pull request by gronostajo**

### CODE REVIEW

**Comment by kwilliams1987** [comment]
It's all your, where can I send your link?

**Comment by gronostajo** [comment]
Could you please send it to the email address from my commit? I'd rather not post it in plaintext :)

**Comment by kwilliams1987** [comment]
Your email isn't visible to me either, create a 10min mail account and I'll post the link to you.

**Comment by gronostajo** [comment]
Hm, I guess there's a privacy setting that hides some emails?

Let's try this one: tkolhcslhefrseruuu@etochq.com

And thanks a lot!

**Comment by kwilliams1987** [comment]
Sent :)

**Pull request merged**
