### PR TITLE
Borderlands 3

### PR DESCRIPTION
**Pull request by JourneyOver**
Game Request
------------

Game requested:

# Prerequisites

- I confirm that this game:
  - [x] is for personal use and will not be sold on.
  - [x] will not be horded and never used.
- [x] Email address: [removed]

# Checklist

- [x] Only one game requested.
- [x] PR title is name of game.
- [x] Moved game from `AVAILABLE.md` to `CLAIMED.md`.
- [x] Changed status icon to ❌.

### CODE REVIEW

**Comment by kwilliams1987** [comment]
Did you want the Steam or Epic version? I can only claim one.

**Comment by JourneyOver** [comment]
@kwilliams1987 I'll take the steam version.

**Comment by kwilliams1987** [comment]
No the claim is only for one or the other. Now the Steam one is claimed the Epic version becomes unclaimable.

If they are both claimable I make separate lines in the document. I've emailed you the code. Enjoy!

**Comment by JourneyOver** [comment]
@kwilliams1987 So I tried to activate the key and it seems to be region restricted sadly, live in the USA, so not sure what region the game is for.

**Comment by kwilliams1987** [comment]
Odd, the keys normally announce if they are region locked and if anything EU/US are almost always interchangeable.

What error message does it give when you try to claim, you didn't have issues with your previous games correct?

**Comment by JourneyOver** [comment]
This is what I get on steam page for redeem:


and this is what I get when trying to redeem through the steam client:



It's funny though because the game is available for sale in the USA on both steam and epic xD

and yea I haven't had any issues with previous games other than when I tried to redeem the [Crash Bandicoot game](https://github.com/kwilliams1987/humble-bundle/pull/21) and it was an already used key.

**Comment by kwilliams1987** [comment]
That's too bad, you can either send me the key and I'll give it to someone
else (in the EU) or use it myself. You can also give it to someone you know
in the EU if you prefer.

If you find another game you like please make a new PR.

Kristian Williams

Email: ***@***.***

**Comment by JourneyOver** [comment]
I will send you the key to your email, and will see if there are any other games currently that I want, if not I might wait to see if anything in the future comes up that you might put up on this repo that interests me.

**Comment by JourneyOver** [comment]
@kwilliams1987 have sent the key back to you! I'll take a look later and see if there is any other game I may want right now, as I'm heading to bed right now since it's almost 5 in the morning and I feel like crap xD

**Comment by kwilliams1987** [comment]
Thanks for your honesty and glad you've been enjoying the games so far. Hopefully I've not deprived you of too much sleep!

**Pull request merged**
